import { Device, HouseholdQuota, NotificationItem, AppUsageItem, DailyUsagePoint } from '@/types/mizan';

export const INITIAL_HOUSEHOLD_QUOTA: HouseholdQuota = {
  totalGB: 133.3,
  usedGB: 85.3,
  remainingGB: 48.0,
  percentage: 64,
  period: 'monthly',
  resetDate: '2026-09-01',
  daysRemaining: 13,
  firstAlertPercent: 80,
  secondAlertPercent: 95,
};

export const TOP_GLOBAL_APPS: AppUsageItem[] = [
  {
    id: 'app-tiktok',
    name: 'TikTok',
    nameAr: 'تيك توك',
    category: 'فيديو وترفيه',
    usedGB: 30.0,
    percentage: 35.2,
    iconName: 'video',
  },
  {
    id: 'app-youtube',
    name: 'YouTube',
    nameAr: 'يوتيوب',
    category: 'فيديو وموسيقى',
    usedGB: 15.0,
    percentage: 17.6,
    iconName: 'play-circle',
  },
  {
    id: 'app-netflix',
    name: 'Netflix',
    nameAr: 'نتفليكس',
    category: 'أفلام ومسلسلات',
    usedGB: 12.4,
    percentage: 14.5,
    iconName: 'tv',
  },
  {
    id: 'app-facebook',
    name: 'Facebook',
    nameAr: 'فيسبوك',
    category: 'تواصل اجتماعي',
    usedGB: 5.0,
    percentage: 5.8,
    iconName: 'share-2',
  },
  {
    id: 'app-instagram',
    name: 'Instagram',
    nameAr: 'إنستغرام',
    category: 'صور وفيديو',
    usedGB: 4.2,
    percentage: 4.9,
    iconName: 'camera',
  },
  {
    id: 'app-whatsapp',
    name: 'WhatsApp',
    nameAr: 'واتساب',
    category: 'مراسلة ومكالمات',
    usedGB: 2.1,
    percentage: 2.5,
    iconName: 'message-circle',
  },
];

export const HOUSEHOLD_7DAY_USAGE: DailyUsagePoint[] = [
  { dayKey: 'sat', dayLabel: 'السبت', usedGB: 12.4, averageGB: 11.8 },
  { dayKey: 'sun', dayLabel: 'الأحد', usedGB: 9.8, averageGB: 11.8 },
  { dayKey: 'mon', dayLabel: 'الإثنين', usedGB: 14.2, averageGB: 11.8 },
  { dayKey: 'tue', dayLabel: 'الثلاثاء', usedGB: 10.5, averageGB: 11.8 },
  { dayKey: 'wed', dayLabel: 'الأربعاء', usedGB: 13.1, averageGB: 11.8 },
  { dayKey: 'thu', dayLabel: 'الخميس', usedGB: 16.5, averageGB: 11.8 },
  { dayKey: 'fri', dayLabel: 'الجمعة', usedGB: 8.8, averageGB: 11.8 },
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev-momen',
    name: 'هاتف مؤمن',
    ownerName: 'مؤمن',
    deviceType: 'phone',
    model: 'Samsung Galaxy S24 Ultra',
    ipAddress: '192.168.1.102',
    macAddress: '8A:3F:1C:4E:91:02',
    usedGB: 38.5,
    allowedQuotaGB: 50.0,
    status: 'connected',
    isPaused: false,
    lastUpdated: 'منذ دقيقتين',
    lastUpdatedDetail: 'اليوم، 04:22 م',
    wifiSSID: 'Mizan_Home_5G',
    customQuota: true,
    topApps: [
      { id: '1', name: 'YouTube', nameAr: 'يوتيوب', category: 'فيديو', usedGB: 12.8, percentage: 33.2, iconName: 'play-circle' },
      { id: '2', name: 'TikTok', nameAr: 'تيك توك', category: 'فيديو', usedGB: 10.4, percentage: 27.0, iconName: 'video' },
      { id: '3', name: 'PUBG Mobile', nameAr: 'ببجي موبايل', category: 'ألعاب', usedGB: 6.2, percentage: 16.1, iconName: 'gamepad-2' },
      { id: '4', name: 'Instagram', nameAr: 'إنستغرام', category: 'تواصل', usedGB: 4.1, percentage: 10.6, iconName: 'camera' },
      { id: '5', name: 'WhatsApp', nameAr: 'واتساب', category: 'محادثات', usedGB: 1.8, percentage: 4.6, iconName: 'message-circle' },
    ],
    dailyUsage: [
      { dayKey: 'sat', dayLabel: 'السبت', usedGB: 5.4, averageGB: 5.5 },
      { dayKey: 'sun', dayLabel: 'الأحد', usedGB: 4.8, averageGB: 5.5 },
      { dayKey: 'mon', dayLabel: 'الإثنين', usedGB: 6.2, averageGB: 5.5 },
      { dayKey: 'tue', dayLabel: 'الثلاثاء', usedGB: 5.1, averageGB: 5.5 },
      { dayKey: 'wed', dayLabel: 'الأربعاء', usedGB: 5.9, averageGB: 5.5 },
      { dayKey: 'thu', dayLabel: 'الخميس', usedGB: 7.1, averageGB: 5.5 },
      { dayKey: 'fri', dayLabel: 'الجمعة', usedGB: 4.0, averageGB: 5.5 },
    ],
    activities: [
      { id: 'act-1', title: 'مزامنة قياسات الاستهلاك مع الراوتر', timeAgo: 'منذ 5 دقائق', type: 'sync' },
      { id: 'act-2', title: 'تخطي حاجز 35 جيجابايت لهذا الشهر', timeAgo: 'منذ ساعتين', type: 'warning' },
      { id: 'act-3', title: 'تجديد تخصيص الحصة إلى 50 جيجابايت', timeAgo: 'منذ 4 أيام', type: 'quota_change' },
    ],
  },
  {
    id: 'dev-sister',
    name: 'هاتف أختي',
    ownerName: 'أختي',
    deviceType: 'phone',
    model: 'Apple iPhone 15 Pro',
    ipAddress: '192.168.1.105',
    macAddress: 'C4:2B:99:A1:77:43',
    usedGB: 27.6,
    allowedQuotaGB: 30.0,
    status: 'warning',
    isPaused: false,
    lastUpdated: 'منذ 5 دقائق',
    lastUpdatedDetail: 'اليوم، 04:19 م',
    wifiSSID: 'Mizan_Home_5G',
    customQuota: true,
    topApps: [
      { id: '1', name: 'TikTok', nameAr: 'تيك توك', category: 'فيديو قصير', usedGB: 15.2, percentage: 55.0, iconName: 'video' },
      { id: '2', name: 'Instagram', nameAr: 'إنستغرام', category: 'تواصل', usedGB: 6.8, percentage: 24.6, iconName: 'camera' },
      { id: '3', name: 'Pinterest', nameAr: 'بينتريست', category: 'صور وتصميم', usedGB: 3.1, percentage: 11.2, iconName: 'image' },
      { id: '4', name: 'WhatsApp', nameAr: 'واتساب', category: 'مراسلة', usedGB: 1.5, percentage: 5.4, iconName: 'message-circle' },
    ],
    dailyUsage: [
      { dayKey: 'sat', dayLabel: 'السبت', usedGB: 4.1, averageGB: 3.9 },
      { dayKey: 'sun', dayLabel: 'الأحد', usedGB: 3.5, averageGB: 3.9 },
      { dayKey: 'mon', dayLabel: 'الإثنين', usedGB: 4.8, averageGB: 3.9 },
      { dayKey: 'tue', dayLabel: 'الثلاثاء', usedGB: 3.8, averageGB: 3.9 },
      { dayKey: 'wed', dayLabel: 'الأربعاء', usedGB: 4.4, averageGB: 3.9 },
      { dayKey: 'thu', dayLabel: 'الخميس', usedGB: 5.2, averageGB: 3.9 },
      { dayKey: 'fri', dayLabel: 'الجمعة', usedGB: 2.8, averageGB: 3.9 },
    ],
    activities: [
      { id: 'act-s1', title: 'إرسال تنبيه: استهلاك 92% من الحصة المحددة', timeAgo: 'منذ 15 دقيقة', type: 'warning' },
      { id: 'act-s2', title: 'تجاوز حد الاستهلاك اليومي المتوقع', timeAgo: 'منذ 3 ساعات', type: 'warning' },
      { id: 'act-s3', title: 'اتصال تلقائي بشبكة Mizan_Home_5G', timeAgo: 'اليوم 09:00 ص', type: 'sync' },
    ],
  },
  {
    id: 'dev-brother',
    name: 'هاتف أخي',
    ownerName: 'أخي',
    deviceType: 'phone',
    model: 'Xiaomi 13T',
    ipAddress: '192.168.1.109',
    macAddress: 'F0:79:59:D3:10:8B',
    usedGB: 19.2,
    allowedQuotaGB: 18.0,
    status: 'blocked',
    isPaused: true,
    lastUpdated: 'منذ 10 دقائق',
    lastUpdatedDetail: 'اليوم، 04:14 م',
    wifiSSID: 'Mizan_Home_2.4G',
    customQuota: true,
    topApps: [
      { id: '1', name: 'YouTube', nameAr: 'يوتيوب', category: 'فيديو عالي الدقة', usedGB: 8.5, percentage: 44.2, iconName: 'play-circle' },
      { id: '2', name: 'Free Fire', nameAr: 'فري فاير', category: 'ألعاب أونلاين', usedGB: 5.4, percentage: 28.1, iconName: 'gamepad-2' },
      { id: '3', name: 'Facebook', nameAr: 'فيسبوك', category: 'فيديو وتصفح', usedGB: 3.6, percentage: 18.7, iconName: 'share-2' },
      { id: '4', name: 'Discord', nameAr: 'ديسكورد', category: 'محادثات صوتية', usedGB: 1.2, percentage: 6.2, iconName: 'message-square' },
    ],
    dailyUsage: [
      { dayKey: 'sat', dayLabel: 'السبت', usedGB: 3.2, averageGB: 2.7 },
      { dayKey: 'sun', dayLabel: 'الأحد', usedGB: 2.6, averageGB: 2.7 },
      { dayKey: 'mon', dayLabel: 'الإثنين', usedGB: 3.8, averageGB: 2.7 },
      { dayKey: 'tue', dayLabel: 'الثلاثاء', usedGB: 2.9, averageGB: 2.7 },
      { dayKey: 'wed', dayLabel: 'الأربعاء', usedGB: 3.4, averageGB: 2.7 },
      { dayKey: 'thu', dayLabel: 'الخميس', usedGB: 4.1, averageGB: 2.7 },
      { dayKey: 'fri', dayLabel: 'الجمعة', usedGB: 0.2, averageGB: 2.7 },
    ],
    activities: [
      { id: 'act-b1', title: 'تم إيقاف الإنترنت مؤقتاً لتجاوز الحصة الشهرية (106%)', timeAgo: 'منذ 25 دقيقة', type: 'pause' },
      { id: 'act-b2', title: 'تنبيه: اقتراب الحصة من الانتهاء', timeAgo: 'أمس 08:30 م', type: 'warning' },
    ],
  },
  {
    id: 'dev-tv',
    name: 'شاشة الصالة',
    ownerName: 'الأسرة',
    deviceType: 'tv',
    model: 'Samsung QLED 65" 4K',
    ipAddress: '192.168.1.115',
    macAddress: 'D8:96:E0:11:42:0A',
    usedGB: 16.8,
    allowedQuotaGB: 35.0,
    status: 'connected',
    isPaused: false,
    lastUpdated: 'منذ دقيقة',
    lastUpdatedDetail: 'اليوم، 04:23 م',
    wifiSSID: 'Mizan_Home_5G',
    customQuota: false,
    topApps: [
      { id: '1', name: 'Netflix', nameAr: 'نتفليكس', category: 'بث بدقة 4K', usedGB: 11.2, percentage: 66.6, iconName: 'tv' },
      { id: '2', name: 'Shahid', nameAr: 'شاهد VIP', category: 'مسلسلات', usedGB: 3.8, percentage: 22.6, iconName: 'play' },
      { id: '3', name: 'YouTube Kids', nameAr: 'يوتيوب أطفال', category: 'أطفال', usedGB: 1.8, percentage: 10.7, iconName: 'smile' },
    ],
    dailyUsage: [
      { dayKey: 'sat', dayLabel: 'السبت', usedGB: 2.8, averageGB: 2.4 },
      { dayKey: 'sun', dayLabel: 'الأحد', usedGB: 1.9, averageGB: 2.4 },
      { dayKey: 'mon', dayLabel: 'الإثنين', usedGB: 2.4, averageGB: 2.4 },
      { dayKey: 'tue', dayLabel: 'الثلاثاء', usedGB: 2.1, averageGB: 2.4 },
      { dayKey: 'wed', dayLabel: 'الأربعاء', usedGB: 2.6, averageGB: 2.4 },
      { dayKey: 'thu', dayLabel: 'الخميس', usedGB: 3.5, averageGB: 2.4 },
      { dayKey: 'fri', dayLabel: 'الجمعة', usedGB: 1.5, averageGB: 2.4 },
    ],
    activities: [
      { id: 'act-tv1', title: 'مزامنة جلسة البث عالي الدقة', timeAgo: 'منذ ساعة', type: 'sync' },
    ],
  },
  {
    id: 'dev-laptop',
    name: 'كمبيوتر العمل',
    ownerName: 'أبو مؤمن (المسؤول)',
    deviceType: 'laptop',
    model: 'Apple MacBook Pro M3',
    ipAddress: '192.168.1.101',
    macAddress: '3C:06:30:FE:22:98',
    usedGB: 11.2,
    allowedQuotaGB: 25.0,
    status: 'connected',
    isPaused: false,
    lastUpdated: 'الآن',
    lastUpdatedDetail: 'اليوم، 04:24 م',
    wifiSSID: 'Mizan_Home_5G',
    customQuota: false,
    topApps: [
      { id: '1', name: 'Zoom Meetings', nameAr: 'زووم اجتماعات', category: 'اجتماعات فيديو', usedGB: 4.8, percentage: 42.8, iconName: 'video' },
      { id: '2', name: 'Google Drive / Sync', nameAr: 'جوجل درايف', category: 'سحابة وعمل', usedGB: 3.2, percentage: 28.5, iconName: 'cloud' },
      { id: '3', name: 'Chrome Browser', nameAr: 'تصفح وأبحاث', category: 'إنترنت', usedGB: 2.4, percentage: 21.4, iconName: 'globe' },
    ],
    dailyUsage: [
      { dayKey: 'sat', dayLabel: 'السبت', usedGB: 1.2, averageGB: 1.6 },
      { dayKey: 'sun', dayLabel: 'الأحد', usedGB: 1.8, averageGB: 1.6 },
      { dayKey: 'mon', dayLabel: 'الإثنين', usedGB: 2.1, averageGB: 1.6 },
      { dayKey: 'tue', dayLabel: 'الثلاثاء', usedGB: 1.9, averageGB: 1.6 },
      { dayKey: 'wed', dayLabel: 'الأربعاء', usedGB: 1.7, averageGB: 1.6 },
      { dayKey: 'thu', dayLabel: 'الخميس', usedGB: 1.5, averageGB: 1.6 },
      { dayKey: 'fri', dayLabel: 'الجمعة', usedGB: 1.0, averageGB: 1.6 },
    ],
    activities: [
      { id: 'act-lap1', title: 'تسجيل دخول كمسؤول النظام من هذا الجهاز', timeAgo: 'منذ 10 دقائق', type: 'sync' },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'اقترب جهاز أختي من استهلاك الحصة المسموحة',
    description: 'تم استخدام 27.6 جيجابايت من أصل 30 جيجابايت (92%). سيتم إرسال إشعار للمستخدم وتطبيق قيود التهدئة عند الوصول للحد.',
    timestamp: 'منذ 15 دقيقة',
    severity: 'warning',
    deviceId: 'dev-sister',
    isRead: false,
  },
  {
    id: 'notif-2',
    title: 'تم تجاوز الحصة وإيقاف اتصال هاتف أخي تلقائياً',
    description: 'استهلك الجهاز 19.2 جيجابايت من الحصة المحددة (18.0 جيجابايت). تم تفعيل حماية ميزان وإيقاف الوصول للإنترنت بانتظار قرار المسؤول.',
    timestamp: 'منذ 25 دقيقة',
    severity: 'danger',
    deviceId: 'dev-brother',
    isRead: false,
  },
  {
    id: 'notif-3',
    title: 'فقد جهاز شاشة الصالة الاتصال مؤقتاً بالشبكة',
    description: 'لوحظ انقطاع الإشارة لمدة 3 دقائق ثم عاد الاتصال بشكل طبيعي بنطاق 5GHz.',
    timestamp: 'منذ ساعتين',
    severity: 'info',
    deviceId: 'dev-tv',
    isRead: false,
  },
  {
    id: 'notif-4',
    title: 'تم تحديث بيانات الراوتر والمزامنة بنجاح',
    description: 'تمت قراءة عدادات الاستهلاك وسجل الحزم عبر بروتوكول TR-069 من راوتر المنزل (Mizan Gateway).',
    timestamp: 'منذ 3 ساعات',
    severity: 'success',
    isRead: true,
  },
  {
    id: 'notif-5',
    title: 'تنبيه استهلاك عام: استهلك المنزل 64% من الباقة الكلية',
    description: 'إجمالي المستخدم 85.3 جيجابايت من أصل 133.3 جيجابايت مع بقاء 13 يوماً على موعد التجديد الشهري.',
    timestamp: 'أمس 09:00 م',
    severity: 'info',
    isRead: true,
  },
];
